# Jekyll configuration for Symbiont Documentation
# Using just-the-docs theme

title: Symbiont Documentation
description: >-
  AI-native, privacy-first programming language and agent framework for 
  autonomous, policy-aware software development.

baseurl: "/docs"
url: "https://symbiont.dev"

# Theme configuration
theme: just-the-docs
color_scheme: dark

# Navigation structure
nav_sort: case_insensitive

# Search configuration
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Heading anchors
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2025 ThirdKey. All rights reserved."

# Repository information
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/thirdkey/symbiont"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Plugin configuration
plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache

# Kramdown configuration
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Exclude files
exclude:
  - node_modules/
  - "*.gemspec"
  - "*.gem"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile

# Collections
collections:
  docs:
    permalink: "/:collection/:name/"
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red