[package]
name = "repl-lsp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "repl-lsp"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tower-lsp = "0.20"
serde_json = "1.0"
repl-core = { path = "../repl-core" }