use clap::ArgMatches;
use std::fs;
use std::path::Path;
use symbi_runtime::AgentRuntime;
use symbi_runtime::http_input::{start_http_input, HttpInputConfig};
use symbi_runtime::RuntimeConfig;
use symbi_runtime::SecretsConfig;
use symbi_runtime::types::AgentId;
use std::sync::Arc;

pub async fn run(matches: &ArgMatches) {
    let port = matches.get_one::<String>("port").unwrap();
    let http_port = matches.get_one::<String>("http-port").unwrap();
    let http_token = matches.get_one::<String>("http-token");
    let http_cors = matches.get_flag("http-cors");
    let http_audit = matches.get_flag("http-audit");
    let preset = matches.get_one::<String>("preset");

    println!("✓ Starting Symbiont runtime...");

    // Create symbi.quick.toml if it doesn't exist
    if !Path::new("symbi.toml").exists() && !Path::new("symbi.quick.toml").exists() {
        create_quick_config(http_token.map(|s| s.as_str()));
        println!("✓ Created symbi.quick.toml with development defaults");
    }

    // Scan agents directory
    let agents_found = scan_agents_directory();

    println!("✓ Runtime started on :{}", port);
    println!("✓ HTTP Input enabled on :{}", http_port);

    if let Some(agent) = agents_found.first() {
        println!("→ Auto-routing /webhook → {}", agent);
    }

    if http_token.is_none() {
        println!("→ Dev token: dev (insecure, rotate in production)");
        println!("⚠️  Warning: Using insecure default token. Set --http.token for production.");
    }

    if let Some(preset_name) = preset {
        println!("→ Using preset: {}", preset_name);
    }

    if http_cors {
        println!("→ CORS enabled with sensible defaults");
    }

    if http_audit {
        println!("→ HTTP audit logging enabled");
    }

    println!("\n📝 Next steps:");
    println!("  • Test webhook: curl -H \"Authorization: Bearer dev\" http://localhost:{}/webhook -d '{{\"test\":true}}'", http_port);
    println!("  • View status: symbi status");
    println!("  • View logs: symbi logs -f");
    println!("\nPress Ctrl+C to stop the runtime");

    let runtime = Arc::new(AgentRuntime::new(RuntimeConfig::default()).await.unwrap());

    let agent_id = if let Some(agent) = agents_found.first() {
        let dsl_path = format!("agents/{}", agent);
        let dsl = fs::read_to_string(&dsl_path).expect("Failed to read DSL file");
        let request = CreateAgentRequest {
            name: agent.strip_suffix(".dsl").unwrap_or(agent).to_string(),
            dsl,
        };
        let response = runtime.create_agent(request).await.expect("Failed to create agent");
        AgentId::parse_str(&response.id).expect("Invalid agent ID")
    } else {
        AgentId::new()
    };

    let http_config = HttpInputConfig {
        bind_address: "0.0.0.0".to_string(),
        port: http_port.parse::<u16>().unwrap(),
        path: "/webhook".to_string(),
        agent: agent_id,
        auth_header: http_token.cloned(),
        cors_enabled: http_cors,
        audit_enabled: http_audit,
        concurrency: 10,
        max_body_bytes: 1_048_576,
        routing_rules: None,
        response_control: None,
    };

    let secrets_config = SecretsConfig::default();

    tokio::select! {
        _ = start_http_input(http_config, Some(runtime.clone()), Some(secrets_config)) => {},
        _ = tokio::signal::ctrl_c() => {}
    }

    runtime.shutdown().await.unwrap();
    println!("\n✓ Runtime stopped");
}

fn create_quick_config(http_token: Option<&str>) {
    let token = http_token.unwrap_or("dev");
    let config = format!(
        r#"# Symbiont Quick Start Configuration
# Generated by symbi up

[runtime]
mode = "dev"
hot_reload = true

[http]
enabled = true
port = 8081
dev_token = "{}"

[storage]
type = "sqlite"
path = "./symbi.db"

[logging]
level = "info"
format = "pretty"
"#,
        token
    );

    fs::write("symbi.quick.toml", config).expect("Failed to create symbi.quick.toml");
}

fn scan_agents_directory() -> Vec<String> {
    let agents_dir = Path::new("agents");
    let mut agents = Vec::new();

    if agents_dir.exists() && agents_dir.is_dir() {
        if let Ok(entries) = fs::read_dir(agents_dir) {
            for entry in entries.flatten() {
                if let Some(ext) = entry.path().extension() {
                    if ext == "dsl" {
                        if let Some(name) = entry.path().file_name() {
                            agents.push(name.to_string_lossy().to_string());
                        }
                    }
                }
            }
        }
    }

    agents
}
